<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.547">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Furong Wang">
<meta name="dcterms.date" content="2025-04-07">

<title>Module 05: Lab 02</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="lab08-furongwang_files/libs/clipboard/clipboard.min.js"></script>
<script src="lab08-furongwang_files/libs/quarto-html/quarto.js"></script>
<script src="lab08-furongwang_files/libs/quarto-html/popper.min.js"></script>
<script src="lab08-furongwang_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="lab08-furongwang_files/libs/quarto-html/anchor.min.js"></script>
<link href="lab08-furongwang_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="lab08-furongwang_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="lab08-furongwang_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="lab08-furongwang_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="lab08-furongwang_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#objectives" id="toc-objectives" class="nav-link active" data-scroll-target="#objectives">Objectives</a></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setup</a></li>
  <li><a href="#load-the-dataset" id="toc-load-the-dataset" class="nav-link" data-scroll-target="#load-the-dataset"><span class="header-section-number">1</span> Load the Dataset</a></li>
  <li><a href="#feature-engineering" id="toc-feature-engineering" class="nav-link" data-scroll-target="#feature-engineering"><span class="header-section-number">2</span> Feature Engineering</a></li>
  <li><a href="#traintest-split" id="toc-traintest-split" class="nav-link" data-scroll-target="#traintest-split"><span class="header-section-number">3</span> Train/Test Split</a></li>
  <li><a href="#linear-regression" id="toc-linear-regression" class="nav-link" data-scroll-target="#linear-regression"><span class="header-section-number">4</span> Linear Regression</a>
  <ul class="collapse">
  <li><a href="#generalized-linear-regression-summary" id="toc-generalized-linear-regression-summary" class="nav-link" data-scroll-target="#generalized-linear-regression-summary"><span class="header-section-number">4.1</span> Generalized Linear Regression Summary</a></li>
  </ul></li>
  <li><a href="#diagnostic-plot" id="toc-diagnostic-plot" class="nav-link" data-scroll-target="#diagnostic-plot"><span class="header-section-number">5</span> Diagnostic Plot</a></li>
  <li><a href="#evaluation" id="toc-evaluation" class="nav-link" data-scroll-target="#evaluation"><span class="header-section-number">6</span> Evaluation</a>
  <ul class="collapse">
  <li><a href="#model-evaluation-plot" id="toc-model-evaluation-plot" class="nav-link" data-scroll-target="#model-evaluation-plot"><span class="header-section-number">6.1</span> Model Evaluation Plot</a></li>
  </ul></li>
  <li><a href="#submission" id="toc-submission" class="nav-link" data-scroll-target="#submission">Submission</a></li>
  <li><a href="#resources" id="toc-resources" class="nav-link" data-scroll-target="#resources">Resources</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Module 05: Lab 02</h1>
<p class="subtitle lead">Regression Modeling on Employment Data</p>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Furong Wang </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Boston University
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 7, 2025</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">April 11, 2025</p>
    </div>
  </div>
    
  </div>
  


</header>


<section id="objectives" class="level1 unnumbered">
<h1 class="unnumbered">Objectives</h1>
<ol type="1">
<li>Use <strong>PySpark</strong> to process the Lightcast dataset.</li>
<li>Engineer features from structured columns for salary prediction.</li>
<li>Train <strong>Linear Regression model</strong>.</li>
<li>Evaluate models using <strong>RMSE</strong> and <strong>R²</strong>.</li>
<li>Visualize predictions using diagnostic plots.</li>
<li>Push work to GitHub and submit the repository link.</li>
</ol>
</section>
<section id="setup" class="level1 unnumbered">
<h1 class="unnumbered">Setup</h1>
<p>The instruction below provides you with general keywords for columns used in the lightcast file. See the data schema generated after the load dataset code above to use proper column name. For visualizations, tables, or summaries, please <strong>customize colors, fonts, and styles</strong> as appropriate to avoid a <strong>2.5-point deduction</strong>. Also, <strong>provide a two-sentence explanation</strong> describing key insights drawn from each section’s code and outputs.</p>
<ol type="1">
<li>Follow the steps below as necessary, use your best judgement in importing/installing/creating/saving files as needed.</li>
<li>Create a new Jupyter Notebook in your <code>ad688-sp25-lab08</code> directory named <code>lab08_yourname.ipynb</code>, if the file exists make sure to change the name.</li>
<li>Use your <strong>EC2 instance</strong> for this lab.</li>
<li>Ensure the <code>lightcast_data.csv</code> file is available on the EC2 instance. if not then <strong>Download the dataset</strong></li>
<li><strong>Add the dataset to <code>.gitignore</code></strong> to avoid pushing large files to GitHub. Open your <code>.gitignore</code> file and add:</li>
<li>Make sure to create a virtual environment and install the required Python libraries if needed, don’t forget to activate it:</li>
<li>Install the required Python libraries if needed, you can also use the given requirement file to install the packages to the virtual environment:</li>
</ol>
<div class="sourceCode" id="cb1"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="ex">python3</span> <span class="at">-m</span> venv .venv</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="bu">source</span> .venv/bin/activate</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="ex">gdown</span> https://drive.google.com/uc<span class="pp">?</span>id=1V2GCHGt2dkFGqVBeoUFckU4IhUgk4ocQ</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="bu">echo</span> <span class="st">"lightcast_job_postings.csv"</span> <span class="op">&gt;&gt;</span> .gitignore</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="ex">pip</span> install <span class="at">-r</span> requirements.txt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="load-the-dataset" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Load the Dataset</h1>
<ol type="1">
<li><strong>Load the Raw Dataset</strong>:
<ul>
<li>Use Pyspark to the <code>lightcast_data.csv</code> file into a DataFrame:</li>
<li>You can reuse the previous code.</li>
<li><span class="uured-bold">Copying code from your friend constitutes plagiarism. DO NOT DO THIS</span>.</li>
</ul></li>
</ol>
<div id="f13e2fb0" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.sql <span class="im">import</span> SparkSession</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> plotly.express <span class="im">as</span> px</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> plotly.io <span class="im">as</span> pio</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>pio.renderers.default <span class="op">=</span> <span class="st">"notebook"</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Initialize Spark Session</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>spark <span class="op">=</span> SparkSession.builder.appName(<span class="st">"LightcastData"</span>).getOrCreate()</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Load Data</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> spark.read.option(<span class="st">"header"</span>, <span class="st">"true"</span>).option(<span class="st">"inferSchema"</span>, <span class="st">"true"</span>).option(<span class="st">"multiLine"</span>,<span class="st">"true"</span>).option(<span class="st">"escape"</span>, <span class="st">"</span><span class="ch">\"</span><span class="st">"</span>).csv(<span class="st">"./data/lightcast_job_postings.csv"</span>)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="co"># df.printSchema()</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="co"># df.show(5)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
25/04/11 02:39:35 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[Stage 1:&gt;                                                          (0 + 1) / 1]                                                                                </code></pre>
</div>
</div>
</section>
<section id="feature-engineering" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Feature Engineering</h1>
<p>Feature Engineering is a crucial step in preparing your data for machine learning. In this lab, we will focus on the following tasks:</p>
<ol type="1">
<li><strong>Drop rows with missing values</strong> in the target variable and key features.</li>
<li>By now you are already familiar with the code and the data. Based on your understanding please choose any 3 (my code output has 10) variables as:
<ol type="1">
<li>two continuous variables (use your best judgment!)</li>
<li>one categorical.</li>
<li>Your dependent variable (y) is <code>SALARY</code>.</li>
</ol></li>
<li><strong>Convert categorical variables</strong> into numerical representations using <strong>StringIndexer</strong> and <strong>OneHotEncoder</strong>.</li>
<li><strong>Assemble features</strong> into a single vector using <strong>VectorAssembler</strong>.</li>
<li><strong>Split the data</strong> into training and testing sets.</li>
</ol>
<div id="f7b45d45" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.sql.functions <span class="im">import</span> col</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.ml.feature <span class="im">import</span> StringIndexer, OneHotEncoder, VectorAssembler</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.ml <span class="im">import</span> Pipeline</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.dropna(subset<span class="op">=</span>[<span class="st">'DURATION'</span>, <span class="st">'MIN_YEARS_EXPERIENCE'</span>, <span class="st">'EMPLOYMENT_TYPE_NAME'</span>, <span class="st">'SALARY'</span>])</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>categorical_col <span class="op">=</span> [<span class="st">'EMPLOYMENT_TYPE_NAME'</span>]</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>continuous_cols <span class="op">=</span> [<span class="st">'DURATION'</span>, <span class="st">'MIN_YEARS_EXPERIENCE'</span>]</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>indexers <span class="op">=</span> [StringIndexer(inputCol<span class="op">=</span>col, outputCol<span class="op">=</span><span class="ss">f"</span><span class="sc">{</span>col<span class="sc">}</span><span class="ss">_idx"</span>, handleInvalid<span class="op">=</span><span class="st">'skip'</span>) <span class="cf">for</span> col <span class="kw">in</span> categorical_col]</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>encoders <span class="op">=</span> [OneHotEncoder(inputCol<span class="op">=</span><span class="ss">f"</span><span class="sc">{</span>col<span class="sc">}</span><span class="ss">_idx"</span>, outputCol<span class="op">=</span><span class="ss">f"</span><span class="sc">{</span>col<span class="sc">}</span><span class="ss">_vec"</span>) <span class="cf">for</span> col <span class="kw">in</span> categorical_col]</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>assembler <span class="op">=</span> VectorAssembler(</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>    inputCols<span class="op">=</span>continuous_cols <span class="op">+</span> [<span class="ss">f"</span><span class="sc">{</span>col<span class="sc">}</span><span class="ss">_vec"</span> <span class="cf">for</span> col <span class="kw">in</span> categorical_col],</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>    outputCol<span class="op">=</span><span class="st">'features'</span></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>pipeline <span class="op">=</span> Pipeline(stages<span class="op">=</span>indexers <span class="op">+</span> encoders <span class="op">+</span> [assembler])</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> pipeline.fit(df).transform(df)</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>data.select(<span class="st">'SALARY'</span>, <span class="st">'features'</span>).show(<span class="dv">5</span>, <span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 2:&gt;                                                          (0 + 1) / 1]                                                                                [Stage 5:&gt;                                                          (0 + 1) / 1]                                                                                </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>+------+-------------------+
|SALARY|features           |
+------+-------------------+
|192800|[55.0,6.0,1.0,0.0] |
|125900|[18.0,12.0,1.0,0.0]|
|118560|[20.0,5.0,1.0,0.0] |
|192800|[55.0,6.0,1.0,0.0] |
|116500|[16.0,12.0,1.0,0.0]|
+------+-------------------+
only showing top 5 rows
</code></pre>
</div>
</div>
</section>
<section id="traintest-split" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Train/Test Split</h1>
<ul>
<li>Perform a <strong>random split</strong> of the data into training and testing sets.</li>
<li>Set a random seed for reproducibility.</li>
<li>You can choose a number for splitting to your liking, justify your choice.</li>
</ul>
<div id="247a8c0c" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> data.select(<span class="st">'SALARY'</span>, <span class="st">'features'</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>train_data, test_data <span class="op">=</span> data.randomSplit([<span class="fl">0.8</span>, <span class="fl">0.2</span>], seed<span class="op">=</span><span class="dv">688</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>((train_data.count(), <span class="bu">len</span>(train_data.columns)))</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>((test_data.count(), <span class="bu">len</span>(test_data.columns)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 6:&gt;                                                          (0 + 1) / 1]                                                                                [Stage 9:&gt;                                                          (0 + 1) / 1]                                                                                </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>(11565, 2)
(2853, 2)</code></pre>
</div>
</div>
</section>
<section id="linear-regression" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Linear Regression</h1>
<ul>
<li>Train a <strong>Linear Regression</strong> model using the training data. <span class="uured-bold">You will run in to an important issue here. Please make an effort in figuring it by yourself. This is one of the most asked interview questions in CapitalOne’s management recruiting program.</span></li>
<li>Evaluate the model on the test data.</li>
<li>Print the coefficients, intercept, R², RMSE, and MAE.</li>
<li>Use the <code>summary</code> object to extract the coefficients and their standard errors, t-values, and p-values.</li>
<li>Create a DataFrame to display the coefficients, standard errors, t-values, p-values, and confidence intervals.</li>
<li>Interpret the coefficients and their significance and explain the model performance metrics.</li>
</ul>
<div id="8965071e" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.ml.regression <span class="im">import</span> LinearRegression</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>train_data <span class="op">=</span> train_data.withColumn(<span class="st">'SALARY'</span>, col(<span class="st">'SALARY'</span>).cast(<span class="st">"double"</span>))</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>test_data <span class="op">=</span> test_data.withColumn(<span class="st">'SALARY'</span>, col(<span class="st">'SALARY'</span>).cast(<span class="st">"double"</span>))</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>feature_names <span class="op">=</span> assembler.getInputCols()</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>lr <span class="op">=</span> LinearRegression(featuresCol<span class="op">=</span><span class="st">'features'</span>, labelCol<span class="op">=</span><span class="st">'SALARY'</span>, regParam<span class="op">=</span><span class="fl">0.1</span>)</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>lr_model <span class="op">=</span> lr.fit(train_data)</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>summary <span class="op">=</span> lr_model.summary</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>test_results <span class="op">=</span> lr_model.evaluate(test_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 12:&gt;                                                         (0 + 1) / 1]                                                                                [Stage 13:&gt;                                                         (0 + 1) / 1]                                                                                [Stage 14:&gt;                                                         (0 + 1) / 1]                                                                                </code></pre>
</div>
</div>
<div id="ceef689a" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Coefficients and Intercept</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Intercept: </span><span class="sc">{:.4f}</span><span class="st">"</span>.<span class="bu">format</span>(lr_model.intercept))</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Coefficients:"</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, coef <span class="kw">in</span> <span class="bu">enumerate</span>(lr_model.coefficients):</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>     <span class="bu">print</span>(<span class="ss">f"  Feature </span><span class="sc">{</span>i <span class="op">+</span> <span class="dv">1</span><span class="sc">}</span><span class="ss">: </span><span class="sc">{</span>coef<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Intercept: 83756.4100
Coefficients:
  Feature 1: -34.9407
  Feature 2: 6793.7588
  Feature 3: -75.3839
  Feature 4: -1382.5611</code></pre>
</div>
</div>
<div id="65923f3b" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Model Evaluation</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"R² on test data: </span><span class="sc">{:.4f}</span><span class="st">"</span>.<span class="bu">format</span>(test_results.r2))</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"RMSE on test data: </span><span class="sc">{:.4f}</span><span class="st">"</span>.<span class="bu">format</span>(test_results.rootMeanSquaredError))</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"MAE on test data: </span><span class="sc">{:.4f}</span><span class="st">"</span>.<span class="bu">format</span>(test_results.meanAbsoluteError))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>R² on test data: 0.2649
RMSE on test data: 36687.7355
MAE on test data: 28336.4387</code></pre>
</div>
</div>
<div id="d9328c36" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the coefficient table</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> tabulate <span class="im">import</span> tabulate</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>coefs <span class="op">=</span> [lr_model.intercept] <span class="op">+</span> <span class="bu">list</span>(lr_model.coefficients)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>se <span class="op">=</span> <span class="bu">list</span>(summary.coefficientStandardErrors)</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>tvals <span class="op">=</span> <span class="bu">list</span>(summary.tValues)</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>pvals <span class="op">=</span> <span class="bu">list</span>(summary.pValues)</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>ci_low <span class="op">=</span> [c <span class="op">-</span> <span class="fl">1.96</span> <span class="op">*</span> s <span class="cf">for</span> c, s <span class="kw">in</span> <span class="bu">zip</span>(coefs, se)]</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>ci_high <span class="op">=</span> [c <span class="op">+</span> <span class="fl">1.96</span> <span class="op">*</span> s <span class="cf">for</span> c, s <span class="kw">in</span> <span class="bu">zip</span>(coefs, se)]</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>features <span class="op">=</span> [<span class="st">"Intercept"</span>] <span class="op">+</span>  [<span class="ss">f"Feature_</span><span class="sc">{</span>i<span class="sc">}</span><span class="ss">"</span> <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>, <span class="bu">len</span>(coefs))]</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a><span class="co"># print("---This is Diagnostic check, No need to print it in the final doc---")</span></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a><span class="co"># print("Length of features:", len(features))</span></span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a><span class="co"># print("Length of coefs:", len(coefs))</span></span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a><span class="co"># print("Length of se:", len(se))</span></span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a><span class="co"># print("Length of tvals:", len(tvals))</span></span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a><span class="co"># print("Length of pvals:", len(pvals))</span></span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a>coef_table <span class="op">=</span> pd.DataFrame({</span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Feature"</span>: features,</span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Estimate"</span>: [<span class="ss">f"</span><span class="sc">{</span>c<span class="sc">:.4f}</span><span class="ss">"</span> <span class="cf">for</span> c <span class="kw">in</span> coefs],</span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Std Error"</span>: [<span class="ss">f"</span><span class="sc">{</span>s<span class="sc">:.4f}</span><span class="ss">"</span> <span class="cf">for</span> s <span class="kw">in</span> se],</span>
<span id="cb16-24"><a href="#cb16-24" aria-hidden="true" tabindex="-1"></a>    <span class="st">"t-stat"</span>: [<span class="ss">f"</span><span class="sc">{</span>t<span class="sc">:.4f}</span><span class="ss">"</span> <span class="cf">for</span> t <span class="kw">in</span> tvals],</span>
<span id="cb16-25"><a href="#cb16-25" aria-hidden="true" tabindex="-1"></a>    <span class="st">"P-Value"</span>: [<span class="ss">f"</span><span class="sc">{</span>p<span class="sc">:.4f}</span><span class="ss">"</span> <span class="cf">for</span> p <span class="kw">in</span> pvals],</span>
<span id="cb16-26"><a href="#cb16-26" aria-hidden="true" tabindex="-1"></a>    <span class="st">"CI Lower"</span>: [<span class="ss">f"</span><span class="sc">{</span>cl<span class="sc">:.4f}</span><span class="ss">"</span> <span class="cf">for</span> cl <span class="kw">in</span> ci_low],</span>
<span id="cb16-27"><a href="#cb16-27" aria-hidden="true" tabindex="-1"></a>    <span class="st">"CI Upper"</span>: [<span class="ss">f"</span><span class="sc">{</span>ch<span class="sc">:.4f}</span><span class="ss">"</span> <span class="cf">for</span> ch <span class="kw">in</span> ci_high]</span>
<span id="cb16-28"><a href="#cb16-28" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb16-29"><a href="#cb16-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-30"><a href="#cb16-30" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(tabulate(coef_table, headers<span class="op">=</span><span class="st">"keys"</span>, tablefmt<span class="op">=</span><span class="st">"pretty"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>+---+-----------+------------+-----------+---------+---------+------------+------------+
|   |  Feature  |  Estimate  | Std Error | t-stat  | P-Value |  CI Lower  |  CI Upper  |
+---+-----------+------------+-----------+---------+---------+------------+------------+
| 0 | Intercept | 83756.4100 |  23.3778  | -1.4946 | 0.1350  | 83710.5894 | 83802.2305 |
| 1 | Feature_1 |  -34.9407  | 101.3466  | 67.0349 | 0.0000  | -233.5801  |  163.6986  |
| 2 | Feature_2 | 6793.7588  | 2917.7812 | -0.0258 | 0.9794  | 1074.9076  | 12512.6099 |
| 3 | Feature_3 |  -75.3839  | 3485.6145 | -0.3966 | 0.6916  | -6907.1884 | 6756.4206  |
| 4 | Feature_4 | -1382.5611 | 2950.7681 | 28.3846 | 0.0000  | -7166.0665 | 4400.9443  |
+---+-----------+------------+-----------+---------+---------+------------+------------+</code></pre>
</div>
</div>
<p>The <code>Intercept</code> is the baseline salary when all features are zero. Not statistically significant (p &gt; 0.05), so we can’t say it differs from zero with confidence. Feature 1 <code>DURATION</code> is significant (p &lt; 0.05). All else being equal, each additional day a job posting is posted is associated with a pay reduction of approximately $34. Feature 2 <code>MIN_YEARS_EXPERIENCE</code> is not significant (p &gt;&gt; 0.05). While the 1-year increase shows a predicted salary increase of approximately $6.8K, we cannot trust this effect statistically. Feature 3 <code>Full-time employment</code> is not significant, which implies nearly no effect of being full-time vs.&nbsp;reference category (mix type). Feature 4 <code>Part-time employment</code> is significant. Part-time jobs pay about $1.38K less than the reference category, suggesting a strong and statistically reliable difference.</p>
<p>The <code>R-Squared</code> of this model shows that it explains about 26.5% of the variance in salary. This is modest, suggesting other important predictors are missing or salary is inherently noisy. The <code>RMSE</code> shows that, on average, the model’s predictions are off by around $36.7K. This is relatively high, depending on the salary scale of your dataset. The <code>MAE</code> value shows that the average absolute difference between predicted and actual salaries is about $28.3K, indicating substantial prediction error.</p>
<section id="generalized-linear-regression-summary" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="generalized-linear-regression-summary"><span class="header-section-number">4.1</span> Generalized Linear Regression Summary</h2>
<p>The summary of the Generalized Linear Regression model provides important insights into the model’s performance and the significance of each feature. The coefficients indicate the relationship between each feature and the target variable (salary), while the standard errors, t-values, and p-values help assess the reliability of these estimates.</p>
<ul>
<li>Please interpret them in the context of your data and model.</li>
<li>Feature Names are purposefully not printed in the output. You can use the <code>features</code> variable to print them out.</li>
</ul>
<div id="712493a4" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>pipeline_model <span class="op">=</span> pipeline.fit(df)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>indexer_model <span class="op">=</span> pipeline_model.stages[<span class="dv">0</span>]</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>categories <span class="op">=</span> indexer_model.labels</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>encoded_categories <span class="op">=</span> categories[:<span class="op">-</span><span class="dv">1</span>]</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>encoded_feature_names <span class="op">=</span> [<span class="ss">f"</span><span class="sc">{</span>categorical_col[<span class="dv">0</span>]<span class="sc">}</span><span class="ss">=</span><span class="sc">{</span>cat<span class="sc">}</span><span class="ss">"</span> <span class="cf">for</span> cat <span class="kw">in</span> encoded_categories]</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>feature_names <span class="op">=</span> [<span class="st">'Intercept'</span>] <span class="op">+</span> continuous_cols <span class="op">+</span> encoded_feature_names</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>coef_table_2 <span class="op">=</span> pd.DataFrame({</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Feature"</span>: feature_names,</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Estimate"</span>: [<span class="ss">f"</span><span class="sc">{</span>c<span class="sc">:.4f}</span><span class="ss">"</span> <span class="cf">for</span> c <span class="kw">in</span> coefs],</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Std Error"</span>: [<span class="ss">f"</span><span class="sc">{</span>s<span class="sc">:.4f}</span><span class="ss">"</span> <span class="cf">for</span> s <span class="kw">in</span> se],</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">"t-stat"</span>: [<span class="ss">f"</span><span class="sc">{</span>t<span class="sc">:.4f}</span><span class="ss">"</span> <span class="cf">for</span> t <span class="kw">in</span> tvals],</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">"P-Value"</span>: [<span class="ss">f"</span><span class="sc">{</span>p<span class="sc">:.4f}</span><span class="ss">"</span> <span class="cf">for</span> p <span class="kw">in</span> pvals]</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(tabulate(coef_table_2, headers<span class="op">=</span><span class="st">"keys"</span>, tablefmt<span class="op">=</span><span class="st">"pretty"</span>))</span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>coef_table_2.to_csv(<span class="st">"_output/lr_summary_pretty.csv"</span>, index<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 15:&gt;                                                         (0 + 1) / 1]                                                                                </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>+---+---------------------------------------------+------------+-----------+---------+---------+
|   |                   Feature                   |  Estimate  | Std Error | t-stat  | P-Value |
+---+---------------------------------------------+------------+-----------+---------+---------+
| 0 |                  Intercept                  | 83756.4100 |  23.3778  | -1.4946 | 0.1350  |
| 1 |                  DURATION                   |  -34.9407  | 101.3466  | 67.0349 | 0.0000  |
| 2 |            MIN_YEARS_EXPERIENCE             | 6793.7588  | 2917.7812 | -0.0258 | 0.9794  |
| 3 | EMPLOYMENT_TYPE_NAME=Full-time (&gt; 32 hours) |  -75.3839  | 3485.6145 | -0.3966 | 0.6916  |
| 4 | EMPLOYMENT_TYPE_NAME=Part-time (≤ 32 hours) | -1382.5611 | 2950.7681 | 28.3846 | 0.0000  |
+---+---------------------------------------------+------------+-----------+---------+---------+</code></pre>
</div>
</div>
</section>
</section>
<section id="diagnostic-plot" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Diagnostic Plot</h1>
<p>Diagnostic plots are essential for evaluating the performance of regression models. In this section, we will create several diagnostic plots to assess the linear regression model’s assumptions and performance. There are four (2*2 grid) main plots we will create, you can use <code>seaborn</code> or <code>matplotlib</code> for this:</p>
<ol type="1">
<li><strong>Predicted vs Actual Plot</strong></li>
<li><strong>Residuals vs Predicted Plot</strong></li>
<li><strong>Histogram of Residuals</strong></li>
<li><strong>QQ Plot of Residuals</strong></li>
</ol>
<div id="d5536362" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> scipy.stats <span class="im">as</span> stats</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Load predictions from LR model</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>df_pred <span class="op">=</span> summary.predictions.select(<span class="st">'SALARY'</span>, <span class="st">'prediction'</span>).toPandas()</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute residuals</span></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>df_pred[<span class="st">'residuals'</span>] <span class="op">=</span> df_pred[<span class="st">'SALARY'</span>] <span class="op">-</span> df_pred[<span class="st">'prediction'</span>]</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>df_pred[<span class="st">'fitted'</span>] <span class="op">=</span> df_pred[<span class="st">'prediction'</span>]</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Standardized residuals</span></span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>res_mean <span class="op">=</span> df_pred[<span class="st">'residuals'</span>].mean()</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>res_std <span class="op">=</span> df_pred[<span class="st">'residuals'</span>].std()</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>df_pred[<span class="st">'std_residuals'</span>] <span class="op">=</span> (df_pred[<span class="st">'residuals'</span>] <span class="op">-</span> res_mean) <span class="op">/</span> res_std</span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Square root of standardized residuals (for Scale-Location)</span></span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>df_pred[<span class="st">'sqrt_std_resid'</span>] <span class="op">=</span> np.sqrt(np.<span class="bu">abs</span>(df_pred[<span class="st">'std_residuals'</span>]))</span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">16</span>, <span class="dv">18</span>))</span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a>sns.set_theme(style<span class="op">=</span><span class="st">"whitegrid"</span>)</span>
<span id="cb21-24"><a href="#cb21-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-25"><a href="#cb21-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot 1: Predicted vs Actual</span></span>
<span id="cb21-26"><a href="#cb21-26" aria-hidden="true" tabindex="-1"></a>plt.subplot(<span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">1</span>)</span>
<span id="cb21-27"><a href="#cb21-27" aria-hidden="true" tabindex="-1"></a>sns.scatterplot(x<span class="op">=</span><span class="st">"prediction"</span>, y<span class="op">=</span><span class="st">"SALARY"</span>, data<span class="op">=</span>df_pred, alpha<span class="op">=</span><span class="fl">0.6</span>)</span>
<span id="cb21-28"><a href="#cb21-28" aria-hidden="true" tabindex="-1"></a>plt.plot([df_pred[<span class="st">"SALARY"</span>].<span class="bu">min</span>(), df_pred[<span class="st">"SALARY"</span>].<span class="bu">max</span>()],</span>
<span id="cb21-29"><a href="#cb21-29" aria-hidden="true" tabindex="-1"></a>         [df_pred[<span class="st">"SALARY"</span>].<span class="bu">min</span>(), df_pred[<span class="st">"SALARY"</span>].<span class="bu">max</span>()],</span>
<span id="cb21-30"><a href="#cb21-30" aria-hidden="true" tabindex="-1"></a>         color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>)</span>
<span id="cb21-31"><a href="#cb21-31" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Predicted vs Actual"</span>)</span>
<span id="cb21-32"><a href="#cb21-32" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Predicted Salary"</span>)</span>
<span id="cb21-33"><a href="#cb21-33" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Actual Salary"</span>)</span>
<span id="cb21-34"><a href="#cb21-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-35"><a href="#cb21-35" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot 2: Residuals vs Predicted</span></span>
<span id="cb21-36"><a href="#cb21-36" aria-hidden="true" tabindex="-1"></a>plt.subplot(<span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">2</span>)</span>
<span id="cb21-37"><a href="#cb21-37" aria-hidden="true" tabindex="-1"></a>sns.scatterplot(x<span class="op">=</span><span class="st">"prediction"</span>, y<span class="op">=</span><span class="st">"residuals"</span>, data<span class="op">=</span>df_pred, alpha<span class="op">=</span><span class="fl">0.6</span>)</span>
<span id="cb21-38"><a href="#cb21-38" aria-hidden="true" tabindex="-1"></a>plt.axhline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>)</span>
<span id="cb21-39"><a href="#cb21-39" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Residuals vs Predicted"</span>)</span>
<span id="cb21-40"><a href="#cb21-40" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Predicted Salary"</span>)</span>
<span id="cb21-41"><a href="#cb21-41" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Residuals"</span>)</span>
<span id="cb21-42"><a href="#cb21-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-43"><a href="#cb21-43" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot 3: Histogram of Residuals</span></span>
<span id="cb21-44"><a href="#cb21-44" aria-hidden="true" tabindex="-1"></a>plt.subplot(<span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">3</span>)</span>
<span id="cb21-45"><a href="#cb21-45" aria-hidden="true" tabindex="-1"></a>sns.histplot(df_pred[<span class="st">"residuals"</span>], kde<span class="op">=</span><span class="va">True</span>, bins<span class="op">=</span><span class="dv">30</span>, color<span class="op">=</span><span class="st">'skyblue'</span>)</span>
<span id="cb21-46"><a href="#cb21-46" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Histogram of Residuals"</span>)</span>
<span id="cb21-47"><a href="#cb21-47" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Residuals"</span>)</span>
<span id="cb21-48"><a href="#cb21-48" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Frequency"</span>)</span>
<span id="cb21-49"><a href="#cb21-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-50"><a href="#cb21-50" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot 4: Normal Q-Q</span></span>
<span id="cb21-51"><a href="#cb21-51" aria-hidden="true" tabindex="-1"></a>plt.subplot(<span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">4</span>)</span>
<span id="cb21-52"><a href="#cb21-52" aria-hidden="true" tabindex="-1"></a>stats.probplot(df_pred[<span class="st">"residuals"</span>], dist<span class="op">=</span><span class="st">"norm"</span>, plot<span class="op">=</span>plt)</span>
<span id="cb21-53"><a href="#cb21-53" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"QQ Plot of Residuals"</span>)</span>
<span id="cb21-54"><a href="#cb21-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-55"><a href="#cb21-55" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot 5: Scale-Location</span></span>
<span id="cb21-56"><a href="#cb21-56" aria-hidden="true" tabindex="-1"></a>plt.subplot(<span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">5</span>)</span>
<span id="cb21-57"><a href="#cb21-57" aria-hidden="true" tabindex="-1"></a>sns.scatterplot(x<span class="op">=</span><span class="st">"fitted"</span>, y<span class="op">=</span><span class="st">"sqrt_std_resid"</span>, data<span class="op">=</span>df_pred)</span>
<span id="cb21-58"><a href="#cb21-58" aria-hidden="true" tabindex="-1"></a>plt.axhline(y<span class="op">=</span>np.mean(df_pred[<span class="st">"sqrt_std_resid"</span>]), color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>)</span>
<span id="cb21-59"><a href="#cb21-59" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Scale-Location Plot"</span>)</span>
<span id="cb21-60"><a href="#cb21-60" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Fitted values"</span>)</span>
<span id="cb21-61"><a href="#cb21-61" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Sqrt(Standardized Residuals)"</span>)</span>
<span id="cb21-62"><a href="#cb21-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-63"><a href="#cb21-63" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot 6: Residuals vs Leverage — Approximate</span></span>
<span id="cb21-64"><a href="#cb21-64" aria-hidden="true" tabindex="-1"></a><span class="co"># Note: Leverage &amp; Cook's Distance require X matrix; we approximate using fitted &amp; residual</span></span>
<span id="cb21-65"><a href="#cb21-65" aria-hidden="true" tabindex="-1"></a>plt.subplot(<span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">6</span>)</span>
<span id="cb21-66"><a href="#cb21-66" aria-hidden="true" tabindex="-1"></a>sns.scatterplot(x<span class="op">=</span><span class="st">"fitted"</span>, y<span class="op">=</span><span class="st">"std_residuals"</span>, data<span class="op">=</span>df_pred, alpha<span class="op">=</span><span class="fl">0.6</span>)</span>
<span id="cb21-67"><a href="#cb21-67" aria-hidden="true" tabindex="-1"></a>plt.axhline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>)</span>
<span id="cb21-68"><a href="#cb21-68" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Residuals vs Fitted (Approximation of Leverage)"</span>)</span>
<span id="cb21-69"><a href="#cb21-69" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Fitted Values (Proxy for Leverage)"</span>)</span>
<span id="cb21-70"><a href="#cb21-70" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Standardized Residuals"</span>)</span>
<span id="cb21-71"><a href="#cb21-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-72"><a href="#cb21-72" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb21-73"><a href="#cb21-73" aria-hidden="true" tabindex="-1"></a>plt.savefig(<span class="st">"_output/lr_diagnostic_classic.png"</span>)</span>
<span id="cb21-74"><a href="#cb21-74" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 18:&gt;                                                         (0 + 1) / 1]                                                                                </code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="lab08-furongwang_files/figure-html/cell-10-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<ol type="1">
<li><p><strong>Predicted vs Actual Plot</strong><br>
This plot assesses how well the model’s predictions align with the actual salaries. Ideally, points should lie along the red diagonal line. However, the wide spread around the line indicates that the model struggles with accurate salary prediction, especially at the lower and higher salary ranges. Most points fall below the red line, indicating a tendency to underestimate higher salaries. There’s also noticeable spread, especially for salaries above $150,000, reflecting prediction inaccuracy in the upper range.</p></li>
<li><p><strong>Residuals vs Predicted Plot</strong><br>
This plot helps detect non-linearity and heteroscedasticity. The residuals show no clear pattern, which supports linearity. However, there’s visible heteroscedasticity—residuals spread wider at higher predicted salaries, suggesting increasing variance as salary rises.</p></li>
<li><p><strong>Histogram of Residuals</strong><br>
The histogram shows the distribution of residuals. The histogram is slightly right-skewed but roughly centered around zero, implying minor bias and an approximately normal distribution of residuals. However, there’s a longer tail on the positive side, meaning occasional large underpredictions.</p></li>
<li><p><strong>QQ Plot of Residuals</strong><br>
The QQ plot further assesses the normality of residuals. The residuals generally follow the diagonal line but deviate at both tails, especially the upper one. This suggests departures from normality, likely due to outliers or non-constant variance.</p></li>
<li><p><strong>Scale-Location Plot</strong><br>
This plot checks the homoscedasticity assumption by plotting the square root of standardized residuals. The spread of points increases slightly with fitted values, again indicating heteroscedasticity. This might impact the reliability of confidence intervals and hypothesis testing.</p></li>
<li><p><strong>Residuals vs Fitted (Leverage Approximation)</strong><br>
Most standardized residuals are within ±2, but a few outliers are outside that range, and there’s some vertical clustering at specific fitted values. This could point to influential data points or model limitations at certain salary levels.</p></li>
</ol>
</section>
<section id="evaluation" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Evaluation</h1>
<p>The evaluation of the model is crucial to understand its performance. In this section, we will calculate and visualize the following metrics: 1. <strong>R² (Coefficient of Determination)</strong>: Indicates how well the model explains the variance in the target variable. 2. <strong>RMSE (Root Mean Squared Error)</strong>: Measures the average magnitude of the errors between predicted and actual values.</p>
<div id="2ed5dadc" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.ml.evaluation <span class="im">import</span> RegressionEvaluator</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.sql.functions <span class="im">import</span> col, <span class="bu">pow</span>, sqrt, avg, mean</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> math</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>pred_glr <span class="op">=</span> lr_model.transform(test_data)</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="co"># R²</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>r2_eval <span class="op">=</span> RegressionEvaluator(labelCol<span class="op">=</span><span class="st">"SALARY"</span>, predictionCol<span class="op">=</span><span class="st">"prediction"</span>, metricName<span class="op">=</span><span class="st">"r2"</span>)</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>r2 <span class="op">=</span> r2_eval.evaluate(pred_glr)</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a><span class="co"># BIC calculation</span></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> pred_glr.count() </span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>k <span class="op">=</span> <span class="bu">len</span>(lr_model.coefficients) <span class="op">+</span> <span class="dv">1</span></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>rss <span class="op">=</span> pred_glr.select(<span class="bu">pow</span>(col(<span class="st">"SALARY"</span>) <span class="op">-</span> col(<span class="st">"prediction"</span>), <span class="dv">2</span>).alias(<span class="st">"squared_error"</span>)).agg({<span class="st">"squared_error"</span>: <span class="st">"sum"</span>}).collect()[<span class="dv">0</span>][<span class="dv">0</span>]</span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>bic <span class="op">=</span> n <span class="op">*</span> math.log(rss <span class="op">/</span> n) <span class="op">+</span> k <span class="op">*</span> math.log(n)</span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a><span class="co"># RMSE manually</span></span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>residuals_df <span class="op">=</span> pred_glr.withColumn(<span class="st">"residuals"</span>, col(<span class="st">"SALARY"</span>) <span class="op">-</span> col(<span class="st">"prediction"</span>))</span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a>rmse <span class="op">=</span> math.sqrt(residuals_df.select(mean(<span class="bu">pow</span>(col(<span class="st">"residuals"</span>), <span class="dv">2</span>))).first()[<span class="dv">0</span>])</span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"R²: </span><span class="sc">{</span>r2<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb23-22"><a href="#cb23-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"BIC: </span><span class="sc">{</span>bic<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb23-23"><a href="#cb23-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"RMSE: </span><span class="sc">{</span>rmse<span class="sc">:.2f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 19:&gt;                                                         (0 + 1) / 1]                                                                                [Stage 20:&gt;                                                         (0 + 1) / 1]                                                                                [Stage 23:&gt;                                                         (0 + 1) / 1]                                                                                [Stage 26:&gt;                                                         (0 + 1) / 1]                                                                                </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>R²: 0.2649
BIC: 60010.97
RMSE: 36687.74</code></pre>
</div>
</div>
<ol type="1">
<li><p><strong>R² (0.2649)</strong> indicates that approximately 26.5% of the variation in salary can be explained by the features in our model. While this shows the model captures some meaningful relationships, a large portion of salary variance remains unexplained, suggesting that important predictors may be missing, such as company-specific factors, job roles, or location.</p></li>
<li><p><strong>RMSE (36687.74)</strong> reflects the average prediction error in salary, measured in the same units as the target variable (USD). A high RMSE like this suggests the model struggles to make accurate predictions, likely due to nonlinear effects, noise, or outliers in the data.</p></li>
<li><p><strong>BIC (60010.97)</strong> is a metric that penalizes model complexity. It helps compare models, favoring those with better fit and fewer predictors. Although useful primarily when comparing models, a relatively high BIC here reinforces the idea that our current linear model might be overly simple for capturing salary dynamics.</p></li>
</ol>
<section id="model-evaluation-plot" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="model-evaluation-plot"><span class="header-section-number">6.1</span> Model Evaluation Plot</h2>
<ul>
<li>Display the predicted vs actual salary plot with a red line indicating the ideal fit (y=x).</li>
<li>Use <code>seaborn</code> or <code>matplotlib</code> to create the plot.</li>
<li>Customize the plot with appropriate titles, labels, and legends.</li>
<li>Describe the plot in a few sentences, highlighting key insights and observations.</li>
</ul>
<div id="3b7563f9" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.ml.regression <span class="im">import</span> GeneralizedLinearRegression</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>glr <span class="op">=</span> GeneralizedLinearRegression(</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>    featuresCol<span class="op">=</span><span class="st">'features'</span>,</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>    labelCol<span class="op">=</span><span class="st">'SALARY'</span>,</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>    family<span class="op">=</span><span class="st">"gaussian"</span>,    </span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>    link<span class="op">=</span><span class="st">"identity"</span>,      </span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>    maxIter<span class="op">=</span><span class="dv">10</span>,</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>    regParam<span class="op">=</span><span class="fl">0.1</span></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>glr_model <span class="op">=</span> glr.fit(train_data)</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>summary_glr <span class="op">=</span> glr_model.summary</span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>glr_df <span class="op">=</span> summary_glr.predictions.select(<span class="st">"prediction"</span>, <span class="st">"SALARY"</span>).toPandas()</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate RMSE</span></span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a>predictions <span class="op">=</span> glr_model.transform(test_data)</span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a>predictions <span class="op">=</span> predictions.withColumn(<span class="st">"residual"</span>, col(<span class="st">"SALARY"</span>) <span class="op">-</span> col(<span class="st">"prediction"</span>))</span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a>rmse <span class="op">=</span> predictions.select(mean(<span class="bu">pow</span>(col(<span class="st">"residual"</span>), <span class="dv">2</span>)).alias(<span class="st">"mse"</span>)).first()[<span class="st">"mse"</span>] <span class="op">**</span> <span class="fl">0.5</span></span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-21"><a href="#cb26-21" aria-hidden="true" tabindex="-1"></a><span class="co"># R²</span></span>
<span id="cb26-22"><a href="#cb26-22" aria-hidden="true" tabindex="-1"></a>mean_y <span class="op">=</span> predictions.select(mean(col(<span class="st">"SALARY"</span>))).first()[<span class="dv">0</span>]</span>
<span id="cb26-23"><a href="#cb26-23" aria-hidden="true" tabindex="-1"></a>tss <span class="op">=</span> predictions.select(<span class="bu">pow</span>(col(<span class="st">"SALARY"</span>) <span class="op">-</span> mean_y, <span class="dv">2</span>).alias(<span class="st">"tss"</span>)).groupBy().<span class="bu">sum</span>(<span class="st">"tss"</span>).first()[<span class="dv">0</span>]</span>
<span id="cb26-24"><a href="#cb26-24" aria-hidden="true" tabindex="-1"></a>rss <span class="op">=</span> predictions.select(<span class="bu">pow</span>(col(<span class="st">"residual"</span>), <span class="dv">2</span>).alias(<span class="st">"rss"</span>)).groupBy().<span class="bu">sum</span>(<span class="st">"rss"</span>).first()[<span class="dv">0</span>]</span>
<span id="cb26-25"><a href="#cb26-25" aria-hidden="true" tabindex="-1"></a>r2 <span class="op">=</span> <span class="dv">1</span> <span class="op">-</span> (rss <span class="op">/</span> tss)</span>
<span id="cb26-26"><a href="#cb26-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-27"><a href="#cb26-27" aria-hidden="true" tabindex="-1"></a><span class="co"># AIC and BIC</span></span>
<span id="cb26-28"><a href="#cb26-28" aria-hidden="true" tabindex="-1"></a>aic <span class="op">=</span> summary_glr.aic</span>
<span id="cb26-29"><a href="#cb26-29" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> predictions.count()</span>
<span id="cb26-30"><a href="#cb26-30" aria-hidden="true" tabindex="-1"></a>k <span class="op">=</span> <span class="bu">len</span>(glr_model.coefficients) <span class="op">+</span> <span class="dv">1</span>  </span>
<span id="cb26-31"><a href="#cb26-31" aria-hidden="true" tabindex="-1"></a>bic <span class="op">=</span> n <span class="op">*</span> math.log(rss <span class="op">/</span> n) <span class="op">+</span> k <span class="op">*</span> math.log(n)</span>
<span id="cb26-32"><a href="#cb26-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-33"><a href="#cb26-33" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting Predicted vs Actual</span></span>
<span id="cb26-34"><a href="#cb26-34" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">6</span>))</span>
<span id="cb26-35"><a href="#cb26-35" aria-hidden="true" tabindex="-1"></a>sns.scatterplot(x<span class="op">=</span><span class="st">"SALARY"</span>, y<span class="op">=</span><span class="st">"prediction"</span>, data<span class="op">=</span>glr_df, color<span class="op">=</span><span class="st">"blue"</span>, alpha<span class="op">=</span><span class="fl">0.5</span>, label<span class="op">=</span><span class="st">"Predicted"</span>)</span>
<span id="cb26-36"><a href="#cb26-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-37"><a href="#cb26-37" aria-hidden="true" tabindex="-1"></a>max_val <span class="op">=</span> <span class="bu">max</span>(glr_df[<span class="st">"SALARY"</span>].<span class="bu">max</span>(), glr_df[<span class="st">"prediction"</span>].<span class="bu">max</span>())</span>
<span id="cb26-38"><a href="#cb26-38" aria-hidden="true" tabindex="-1"></a>plt.plot([<span class="dv">0</span>, max_val], [<span class="dv">0</span>, max_val], color<span class="op">=</span><span class="st">"red"</span>, linestyle<span class="op">=</span><span class="st">"--"</span>, label<span class="op">=</span><span class="st">"Ideal Fit (y = x)"</span>)</span>
<span id="cb26-39"><a href="#cb26-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-40"><a href="#cb26-40" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="ss">f"Predicted vs Actual Salary (GLR Model)</span><span class="ch">\n</span><span class="ss">"</span></span>
<span id="cb26-41"><a href="#cb26-41" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"RMSE = </span><span class="sc">{</span>rmse<span class="sc">:.2f}</span><span class="ss"> | R² = </span><span class="sc">{</span>r2<span class="sc">:.4f}</span><span class="ss"> | AIC = </span><span class="sc">{</span>aic<span class="sc">:.2f}</span><span class="ss"> | BIC = </span><span class="sc">{</span>bic<span class="sc">:.2f}</span><span class="ss">"</span>, </span>
<span id="cb26-42"><a href="#cb26-42" aria-hidden="true" tabindex="-1"></a>          loc<span class="op">=</span><span class="st">"left"</span>, fontsize<span class="op">=</span><span class="dv">14</span>, fontweight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb26-43"><a href="#cb26-43" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Actual Salary (USD)"</span>, fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb26-44"><a href="#cb26-44" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Predicted Salary (USD)"</span> , fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb26-45"><a href="#cb26-45" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb26-46"><a href="#cb26-46" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb26-47"><a href="#cb26-47" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb26-48"><a href="#cb26-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-49"><a href="#cb26-49" aria-hidden="true" tabindex="-1"></a><span class="co"># Save figure</span></span>
<span id="cb26-50"><a href="#cb26-50" aria-hidden="true" tabindex="-1"></a>plt.savefig(<span class="st">"_output/glr_predicted_vs_actual.png"</span>)</span>
<span id="cb26-51"><a href="#cb26-51" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 29:&gt;                                                         (0 + 1) / 1]                                                                                [Stage 30:&gt;                                                         (0 + 1) / 1]                                                                                [Stage 31:&gt;                                                         (0 + 1) / 1]                                                                                [Stage 34:&gt;                                                         (0 + 1) / 1]                                                                                [Stage 37:&gt;                                                         (0 + 1) / 1]                                                                                [Stage 40:&gt;                                                         (0 + 1) / 1]                                                                                [Stage 43:&gt;                                                         (0 + 1) / 1]                                                                                [Stage 46:&gt;                                                         (0 + 1) / 1]                                                                                [Stage 47:&gt;                                                         (0 + 1) / 1]                                                                                </code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="lab08-furongwang_files/figure-html/cell-12-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>This plot visualizes the performance of the GLR (Generalized Linear Regression) model. The blue scatter points represent the predicted salaries versus the actual salaries in the test set, while the red dashed line illustrates the ideal scenario where predictions perfectly match actual values.</p>
<p>The plot indicates that predictions tend to cluster around the lower to mid salary range (predominantly under $200,000). This suggests the model performs better at estimating average salary levels but struggles with extreme values. Notable deviations from the red line are observed for higher actual salaries, reflecting the model’s tendency to underestimate salaries in this range. The R² value of 0.2649 reveals that the model explains approximately 26.5% of the variance in salary, hinting at potential non-linear relationships or unaccounted factors. The RMSE of $36,687.74 signifies the typical error magnitude, while the high AIC (275478.23) and BIC (60010.97) underscore the model’s complexity relative to its fit.</p>
<p>In summary, while the model demonstrates reasonable performance in predicting salaries within the central range, its accuracy diminishes significantly for high-income outliers, indicating room for improvement.</p>
</section>
</section>
<section id="submission" class="level1 unnumbered">
<h1 class="unnumbered">Submission</h1>
<ol type="1">
<li>Save figures in the <code>_output/</code> folder.</li>
<li>Commit and push code and output files:</li>
</ol>
<div class="sourceCode" id="cb28"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">git</span> add .</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">git</span> commit <span class="at">-m</span> <span class="st">"Add Lab 08 Salary Prediction models and output"</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">git</span> push origin main</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ol start="3" type="1">
<li>Submit your GitHub repository link.</li>
</ol>
</section>
<section id="resources" class="level1 unnumbered">
<h1 class="unnumbered">Resources</h1>
<ul>
<li><a href="https://spark.apache.org/docs/latest/ml-guide.html">PySpark MLlib Docs</a><br>
</li>
<li><a href="https://seaborn.pydata.org/">Seaborn Docs</a><br>
</li>
<li><a href="https://pandas.pydata.org/docs/user_guide/index.html">Pandas User Guide</a></li>
</ul>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>